export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const USER_SET = "USER_SET"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_REGISTER = "USER_REGISTER"